SHORT_CACHE_TIMEOUT_MINUTES = 1
MEDIUM_CACHE_TIMEOUT_MINUTES = 5
LONG_CACHE_TIMEOUT_MINUTES = 10

POKEMON_API_BASE_URL = "https://pokeapi.co/api/v2/"

URL_LIST_POKEMON = "pokemon"
QUERY_OFFSET_POKEMON = 1
QUERY_LIMIT_POKEMON = 300

URL_LIST_POKEDEX = "pokedex"
QUERY_LIMIT_POKEDEX = 30
